
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Lovely Bones', 'Kevin Lee', 'Chick Lit', '2022-05-25');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Help', 'Michael Davis', 'Graphic Novel', '2022-12-12');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Girl with the Dragon Tattoo', 'Laura Thompson', 'Adventure', '2022-06-08');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Alchemist', 'Sarah Wilson', 'Science Fiction', '2023-01-07');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'To Kill a Mockingbird', 'Daniel Robinson', 'Fantasy', '2024-05-30');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'To Kill a Mockingbird', 'Ethan Murphy', 'Adventure', '2024-04-15');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Stand', 'Alice Smith', 'Cookbook', '2022-09-19');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Hobbit', 'Tyler Cooper', 'Biography', '2022-12-12');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Martian', 'Alice Smith', 'Mystery', '2022-12-12');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Catcher in the Rye', 'Rachel White', 'Adventure', '2023-10-25');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Lord of the Rings', 'Daniel Robinson', 'Cookbook', '2023-09-21');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Kite Runner', 'Emily Brown', 'Young Adult', '2022-03-20');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Help', 'Michael Davis', 'Science Fiction', '2024-05-30');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Shining', 'Hannah Nguyen', 'Thriller', '2022-01-05');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Goldfinch', 'Hannah Nguyen', 'Chick Lit', '2024-01-09');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Lovely Bones', 'Tyler Cooper', 'Romance', '2023-01-07');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'Moby Dick', 'Michael Davis', 'Crime', '2024-01-09');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Giver', 'Hannah Nguyen', 'Chick Lit', '2023-07-16');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'To Kill a Mockingbird', 'Alice Smith', 'Self-Help', '2022-04-10');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Goldfinch', 'Jessica Rodriguez', 'Cookbook', '2024-02-20');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Fault in Our Stars', 'Ethan Murphy', 'Humor', '2023-03-25');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Hunger Games', 'Olivia Garcia', 'Young Adult', '2024-04-15');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Stand', 'Olivia Garcia', 'Self-Help', '2023-06-10');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Lovely Bones', 'Laura Thompson', 'Cookbook', '2023-08-31');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Great Gatsby', 'John Johnson', 'Romance', '2022-09-19');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Da Vinci Code', 'Rachel White', 'Adventure', '2022-09-19');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( '1984', 'Patrick Evans', 'Crime', '2023-10-25');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'Moby Dick', 'Olivia Garcia', 'Romance', '2022-03-20');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'To Kill a Mockingbird', 'David Martinez', 'Young Adult', '2023-10-25');
insert into tbl_books (Title, Author, Genre, PublishedYear) values ( 'The Secret Garden', 'Michael Davis', 'Thriller', '2022-08-30');
